/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ForeignJNITest */

#ifndef _Included_ForeignJNITest
#define _Included_ForeignJNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ForeignJNITest
 * Method:    functionCall
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ForeignJNITest_functionCall
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
