import os, sys, errno
from fuse import FUSE, Operations

class MyDemoFS(Operations):
    def __init__(self):
        # We define a virtual file and its "fake" content
        self.files = {'/hello': b'This content is generated by Python code!\n'}

    # 1. Tell the OS if a path is a file or a directory
    def getattr(self, path, fh=None):
        if path == '/':
            return dict(st_mode=(0o40755), st_nlink=2)
        if path in self.files:
            return dict(st_mode=(0o100644), st_nlink=1, st_size=len(self.files[path]))
        raise OSError(errno.ENOENT)

    # 2. List the contents of a directory
    def readdir(self, path, fh):
        return ['.', '..'] + [name[1:] for name in self.files.keys()]

    # 3. Handle the "read" system call
    def read(self, path, size, offset, fh):
        if path in self.files:
            return self.files[path][offset:offset + size]
        raise OSError(errno.EIO)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: python demo_fs.py <mountpoint>')
        sys.exit(1)
    # Mount the filesystem
    FUSE(MyDemoFS(), sys.argv[1], nothreads=True, foreground=True)