# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_test.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'grpc_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc_test.proto\x12\x07product\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"Z\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x16\n\x0estock_quantity\x18\x04 \x01(\x05\x32X\n\x0eProductService\x12\x46\n\x11GetProductDetails\x12\x17.product.ProductRequest\x1a\x18.product.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=28
  _globals['_PRODUCTREQUEST']._serialized_end=64
  _globals['_PRODUCTRESPONSE']._serialized_start=66
  _globals['_PRODUCTRESPONSE']._serialized_end=156
  _globals['_PRODUCTSERVICE']._serialized_start=158
  _globals['_PRODUCTSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
